# Generated by Django 3.2.12 on 2022-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
